### ISSUE TITLE
Allow to register step options

### ISSUE THREAD

**Issue by josemarluedke** [alexlafroscia/ember-steps#104]
First, thank your for this awesome project. We are looking forward to use it in our projects. We do have a few needs that I hope to have support here.

We would like to be able to register `options` to each step and have access to it using `StepManagerComponent.steps`. 

I think it's best to explain with an example: 

```hbs
{{#step-manager as |w|}}
  {{#each w.steps as |step|}}
    {{step}} <!-- Currently this is just an string -->
    <!-- step could be changed to be an object so we can access more details -->
    {{step.name}}
    {{step.options.title}}
  {{/each}}

  {{#w.step name='first' options=(hash title='This is the first step')}}
     First step content!
  {{/w.step}}

  {{#w.step name='second' options=(hash title='This is the second step')}}
     Second step content!
  {{/w.step}}
{{/step-manager}}

```

With this, it would be possible to generate some type of progress bar with title and links to each step.

It would also be interesting, but not required, to each step object to have some computed values as `isActive`, `hasNext` and `hasPrevious` which is exactly what the step component give us.

**Comment by lougreenwood** [comment]
I believe that I have a similar requirement...

I have a multi-path bombarding flow which I'm using Ember Steps for.

Part of my UI uses a nav bar component with generic `transition-to-prev/next` buttons.

However, some steps branch, on these steps I'd like to be able to define that particular step as having no 'next' (so that my generic next button is hidden) and instead have the particular step define it's own (multiple) named steps to transition to.

I was going to create an issue which suggested allowing some `hasNext` attribute to be set on a per-step basis. This would allow something like `if w.currentStep.hasNext then showNextBtn`, but I imagine something like what I'm describing could also be achieved with options (options could actually allow storing the multiple branches in the step object too)...

So yeah, 👍 for this & yep, @alexlafroscia Ava.js `TestContext` looks like the same concept to me

**Comment by alexlafroscia** [comment]
Cool, glad to have another use-case described!

I'm all for supporting this and making it the next major version of `ember-steps`. I have a branch locally where I started work on it, so I'll keep at it and see what we can do to support this!

**Comment by alexlafroscia** [comment]
Question about the semantics here:

I'm adding the concept of a `Node` that will populate the underlying state machine and contain the step name, as `hasNext` and `hasPrevious` property, and have the `context` object we've discussed here attached to it. Those `Node` objects will be exposed in the `steps` property on the yielded object, just like the original code example here described.

My question is this, then: would you expect `currentStep` to be a `StepName` or a `Node`? If we keep it a `StepName`, if you're building out a progress bar dynamically and are trying to figure out which node is active, you'll have something like this:

```hbs
{{#step-manager as |w|}}
  {{#each w.steps as |step|}}
    {{eq step.name w.currentStep}}
  {{/each}}

  {{#w.step name='first' options=(hash title='This is the first step')}}
     First step content!
  {{/w.step}}

  {{#w.step name='second' options=(hash title='This is the second step')}}
     Second step content!
  {{/w.step}}
{{/step-manager}}
```

but if we change it to a `Node`, I can add an `isActive` property to it

```hbs
{{#step-manager as |w|}}
  {{#each w.steps as |step|}}
    {step.isActive}}
  {{/each}}

  {{#w.step name='first' options=(hash title='This is the first step')}}
     First step content!
  {{/w.step}}

  {{#w.step name='second' options=(hash title='This is the second step')}}
     Second step content!
  {{/w.step}}
{{/step-manager}}
```

which might be more handy.

Things like `transition-to` will be updated to accept either a `Node` or a `StepName` since it's fairly easy to accept either.

**Comment by alexlafroscia** [comment]
Another consideration I'm having now is that you can currently bind to `currentStep` if you need to trigger transitions from a query param or something like that... I guess it should really stay a `StepName`
