### ISSUE TITLE
onActivate hook is not triggered when app entry point is page with onActivate hook

### ISSUE THREAD

**Issue by lougreenwood** [alexlafroscia/ember-steps#129]
Using a page which:

* contains ember-steps
* steps are bound to a query param
* application entry point is something like `http://myapp.com?step=stepWithOnActivateHook`
* see that hook is not triggered

However, if I transition to a different step and back to the `onActivate` step in the same session it then works.

I know this is crappy bug report, I'll put together a repro when I get a chance - just adding the issue so I don't forget :)

**Comment by lougreenwood** [comment]
Here's a repro repo: https://github.com/lougreenwood/ember-steps-problem 👍 

Expected behaviour:
* On app load, step `2`'s `onActivate` hook should fire

Actual behaviour:
* On app load, no `onActivate` hook is fired if step is app entry point
* navigating to another step (step 1) and then back to step 2 in the same session works as expected

**Comment by alexlafroscia** [comment]
What do you think about Chris's suggestion to use `{{did-insert}}` and drop `onActivate`?

I really like the idea -- the less the add-on does, IMO, the better. Now that we have a built-in (or provided as a [first-party addon](https://github.com/emberjs/ember-render-modifiers) way to different events when DOM elements enter or leave the page, I really like the idea of removing the API that we currently provide in the add-on and instead encouraging people to use the element modifier.

So rather than `onActivate` at all, the example from your reproduction (which, by the way, I really appreciate you making!) would look like this:

```hbs
{{#step-manager currentStep=this.tab as |w|}}
  {{#each this.steps as |step|}}
    {{#w.step name=step.name}}
      <div
        {{did-insert (action 'activated')}}
        {{will-destroy (action 'deactivated')}}
      >
        I am step #{{step.label}} with name {{step.name}}.
      </div>
    {{/w.step}}
  {{/each}}
{{/step-manager}}
```

**Comment by lougreenwood** [comment]
Yep, completely agree with this - I've been thinking the same!

**Comment by alexlafroscia** [comment]
Awesome. I will put together a PR that makes that change and we'll do a `9.0` release with these breaking changes!
