### ISSUE TITLE
Routing workflow shortcomings

### ISSUE THREAD

**Issue by davewasmer** [alexlafroscia/ember-steps#142]
Hey @alexlafroscia - thanks for the great addon!

We ran into some use cases that resulting in less than ideal code, so I thought I'd drop this issue here in case (a) there's a better way to use `ember-steps` to accomplish our use cases that we missed, and (b) in case others are facing the same problem. We have some thoughts on how to solve these, but unfortunately don't have time to PR anything this second.

Imagine a multi-step wizard living at `/onboarding`, driven by a query param passed in as the `currentStep` (i.e. `/onboarding?step=one`). Here are the use cases we want to support:

1. A user navigating to `/onboarding` should land on the step they left off on (i.e. the first incomplete step). If they have no progress, they land on the first step.

2. A user navigating to any step prior to where they left off (i.e. an already completed step) should be allowed to land on that step.

3. A user navigating to any step ahead of where they left off should be redirected backwards to the step the left off (i.e. `/onboarding?step=five` redirects to `/onboarding?step=three`, the first incomplete step for that user).

Right now, I'm building this out manually - my route's `model()` hook is examining the query param and trying to determine what step to enter.

Besides the downside of this being (I imagine) a relatively common use case that I end up home-rolling, the other major downside is that now my route has to be aware of the step order in the template. This ends up with two "sources of truth" for the order of steps: the route model hook and the template order.

-------

I think there's likely a solution here where we could pass in an action to each step that would check to see if the user has completed / could enter that step by default. Something like a step validator, but one that fires on initial enter rather than on a button click.

**Comment by alexlafroscia** [comment]
Thanks for the feedback! I'm happy to try to help.

> Right now, I'm building this out manually - my route's model() hook is examining the query param and trying to determine what step to enter.

This, to me, feels like the right thing to do. The idea is that `ember-steps` is completely decoupled from your logic around determining which step should be active. It sounds like you want some kind of state machine that takes in the user's onboarding state, the URL they initially attempt to access, and their navigational choices from there to determine what should be the step that's made active.

> This ends up with two "sources of truth" for the order of steps: the route model hook and the template order.

This is a really good point, though, and I can appreciate wanting a single source of truth for things.

I feel like your business logic should define the ordering if the "natural" template ordering is not enough for you. Your state machine determines the initial step to render, and then leverage the validation helper to determine whether a future navigation is valid.

> I think there's likely a solution here where we could pass in an action to each step that would check to see if the user has completed / could enter that step by default.

Could you write up an example of what that API would look like? There used to be more hooks into what is happening within the components but I ultimately removed them because the API became quite confusing. I'm not sure I want to introduce an API around validating whether you can activate some given step when it's easier (maybe better?) to just provide validation around the `currentStep` variable that you can pass into the `step-manager`.

In your case, I would probably avoid using the provided `transition-to` actions at all and only ever alter the active step by changing the `currentStep` property -- that process can be validated by your business logic to produce the next valid step, or the same step if they are unable to move on.

**Comment by davewasmer** [comment]
Thanks for the quick response!

> The idea is that ember-steps is completely decoupled from your logic around determining which step should be active.

I completely agree about the decoupling here, but I think we can keep them separate by potentially allowing actions/functions to be passed to provide the necessary domain-specific logic

> I feel like your business logic should define the ordering if the "natural" template ordering is not enough for you.

Not sure I agree 100% here.

I think there are two layers of "ordering" we are talking about: which order the steps come in, and where in those steps the user should be.

The logic of "where in these steps is the user?" is definitely beyond the scope of this addon - that's purely implementation specific, and not something that ember-steps should be concerned with directly.

But the order of the steps is, to some extent, unavoidably encoded in the template (unless you simply `{{each steps as |step|}} {{component ...`, but that forces each step into its own component).

> Your state machine determines the initial step to render, and then leverage the validation helper to determine whether a future navigation is valid.

Yep, the validation helper is definitely helpful for this stuff. I just think we could expose something similarly helpful for the initial step. It wouldn't cover _every_ possible use case, but it would help with what I imagine is a very common scenario (the use cases I described, essentially just a resumable wizard).

> In your case, I would probably avoid using the provided transition-to actions at all and only ever alter the active step by changing the currentStep property

This would be disappointing, since those helpers cover exactly what we need out of the box (since the initial step is the only problem).

> Could you write up an example of what that API would look like?

Certainly. Here's a rough first attempt (I haven't thought through every angle here, just a quick stab):

```hbs
{{#step-manager currentStep=stepQueryParam as |m|}}
  {{m.step name="one" isInitial=(action "isStepOneInitial")}}
  {{m.step name="two" isInitial=(action "isStepTwoInitial")}}
  {{m.step name="three" isInitial=(action "isStepThreeInitial")}}
{{/step-manager}}
```

* `isInitial` is a _terrible_ name for this, but figured we could bikeshed that separately if you like the proposal

The default value of `stepQueryParam` would be null. When null, the step manager starts with the first step, and checks if `isStepOneInitial` evaluates to `true`. If not, it advances one step and checks `isStepTwoInitial`, and so on, until the first one returns true, then lands the user there.

Similarly, on initial render, if `stepQueryParam` is _not_ null, then the step manager starts at the request step and checks if `isStepXXXInitial` is true. If not, it steps backward through the steps until it finds the first step that returns true.

The logic for which step to start on lives purely in the consumer's code - this approach merely makes ember-steps aware of such logic and leverage it + the natural template order.

**Comment by alexlafroscia** [comment]
Sorry for the delay; I've been taking a break from GitHub for a bit.

How do you think your approach compares to building the `isStep__X__Initial` logic into something external to the `step-manager`?

```javascript
class MyController extends Controller {
  currentStep;

  init() {
    super.init(...arguments);

    if (this.isStepOneInitial()) {
      this.currentStep = 'one';
    } else if (this.isStepTwoInitial()) {
      this.currentStep = 'two'
    }
  }
}
```

```hbs
{{#step-manager currentStep=currentStep as |w|}}
  {{w.step name='one'}}
  {{w.step name='two'}}
{{/step-manager}}
```

The benefit to this that I see is that it keeps `ember-steps` small and composable. If you need additional business logic around the current step, you can add it in yourself by deriving `currentStep` or `initialStep` from something other than the query param value directly.

What would be your reasoning for adding additional logic to the library in order to have a second way of determining the current step?

**Comment by davewasmer** [comment]
@alexlafroscia no worries - we have implemented something like your suggestions already, so this isn't urgent on our end, more of a "could we make it even better" type of question.

> What would be your reasoning for adding additional logic to the library in order to have a second way of determining the current step?

I'd suggest the goal is determining the initial/default value of the current step, not really a "second way" of determining the current step. This is needed primarily based on the idea that the template could then be the single source of truth for the order of these steps. Your example solution requires that the order of the `if` conditionals inside the controller `init()` match the order of the template.

A bonus is that it would allow simpler `isInitial()` implementations to be fully defined in the template:

```hbs
{{#w.step isInitial=(not user.phone)}}
  <input value={{user.phone}} />
{{/w.step}}
```

A different approach might be to roll up the `isInitial` evaluation to the manager level:

```hbs
{{step-manager pickInitialStep=(action this.pickInitialStep)}}
```
```js
pickInitialStep(steps) {
  // steps would be an array of step names in the order they appear in the template
```

This would basically let the step manager "export" the template-defined order into JS land. But you'd lose the ability to define simple `isInitial`s per step in the template.

-----

All that said, I can see an argument for simplicity here - that having two "sources of truth" when it comes to step order (template and JS code) is the price to pay for a having an easier to maintain and understand library. So if you'd rather not pay the complexity cost, totally understandable.

**Comment by alexlafroscia** [comment]
Thanks for all this feedback -- I greatly appreciate the time, the code examples, and the discussion. I hope my disagreement doesn't come off in a negative way. I've just learned (in particular, with this library) that it's better to keep things small and simple, so this

>  So if you'd rather not pay the complexity cost, totally understandable.

Really rings true for me!

***

>  Your example solution requires that the order of the if conditionals inside the controller init() match the order of the template.

That's a good point, and one I hadn't really thought of.

Can I ask about the number of steps/general complexity of the step managers you're creating? In my cases, it's usually 2-3 steps max, so "manually" keeping the step order in sync doesn't feel like too much overhead. I could see it being a problem with a much bigger set of steps, so I'd love to hear more about your use-case!

I don't think I'd want to have an `isInitial` flag on each of the steps -- I'm concerned that would be pretty confusing since more than one can be true. As you originally described, you have to come up with a lot of rules (things like "it's the first step in order that has the `isInitial` flag" and "if the `initialStep` property is `null`, then go and look for the `isInitial` flag on a step") which would be tough to document, communicate and maintain over time.

In terms of a simple template-only use-case setting a particular step as the "initial" one, I'd much rather you do something like this:

```hbs
{{#step-manager initialStep=(if (not user.phone) 'phone') as |w|}}
  {{#w.step name='phone'}}
    <input value={{user.phone}} />
  {{/w.step}}
{{/step-manager}}
```

I would argue a few improvements

- Only one place to look to determine what the initial step is
- No confusion around multiple steps declaring they are the initial one
- The `step` component continues not to know about or be directly impacted by the internal state machine that manages the sequence of steps

**Comment by davewasmer** [comment]
> hope my disagreement doesn't come off in a negative way

Not at all - and I'm trying not to pester. I honestly think a reasonable answer here could be "not worth the complexity cost", but I figured I'd raise the use case and a potential solution.

> Can I ask about the number of steps/general complexity of the step managers you're creating

Right now we're at 8 steps, likely to only increase.

> that would be pretty confusing since more than one can be true

I think that could at least be partially mitigated with some better naming (i.e. `isComplete` or `canBeFirst`), plus I think the docs would call out exactly how this is typically used: for resumable wizards.

> tough to document, communicate and maintain over time

Fair point

> `{{#step-manager initialStep=(if (not user.phone) 'phone') as |w|}}`

This would rapidly become unwieldy, and still duplicates ordering logic. The `if` conditionals have to match the template order of the steps (it's marginally better since they are co-located right next to each other, but still not ideal).

Our implementation would have to look something like:

```hbs
{{#step-manager initialStep=(
    if (not user.bio) 'bio' (
	  if (not user.headshot) 'headshot' (
 		if (not (and user.primaryRole user.secondaryRole)) 'role' (
			... 5 more steps ...
  ) as |w|}}
```

**Comment by alexlafroscia** [comment]
I definitely understand the pain point around the `initialStep` logic getting complex. 8 steps quite a lot to have to account for, no doubt.

I think I want to keep the library focused, and the complexity of a system for determining the initial step beyond the current means isn't something I'm interested in supporting. I appreciate your understanding!
