### ISSUE TITLE
Dynamic names*

### ISSUE THREAD

**Issue by Gutorov** [alexlafroscia/ember-steps#19]
HI, I have strange issue when I try add dynamic name for tab I get error
`{{#step-manager as |w|}}
    {{#each steps as |st|}}
      {{#w.step name=st.step_content }}
        {{st.name}} {{component st.step_content}}
        <button {{action w.transition-to st.next_step_content}}>
                {{st.button_title}}
            </button>
      {{/w.step}}
    {{/each}}
  {{/step-manager}}`
And error

> MissingPropertyError: `currentStep` must be provided. This should be ensured by the build process. If you're seeing this message, please file a bug report because something is wrong.

But it`s looks strange, possible Im do it wrong...

**Comment by alexlafroscia** [comment]
Yeah, dynamic names don't work yet and I'm not planning to support them in the `v1.0.0` release. I'd liek to support them but it turns out there are some quirks that make it trickier than you'd expect.  

Sorry about that error message, it's not worded that well.  Turns out that, the way the code is written, a dynamic name and not providing one at all looks the same to the `step-manager` so the error thrown. To be honest, I didn't think anyone was using this but me!

To explain a but further (for future reference if other people run into the same issue) dynamic names aren't supported right now because there is essentially a state machine inside of the `step-manager` that maps `currentStepName -> nextStepName`. This is set up during the first render. Having a dynamic step name on the `step` component would break that.

If it suits your use case, you can use the `unbound` helper as long as `st.step_content` doesn't ever change.  That would look something like this (although it does depend on your data specifically)

```hbs
{{#step-manager currentStep=(unbound steps.firstObject.step_content) as |w|}}
  {{#each steps as |st|}}
    {{#w.step name=(unbound st.step_content) }}
      {{st.name}}
      {{component st.step_content}}
      <button {{action w.transition-to st.next_step_content}}>
        {{st.button_title}}
      </button>
    {{/w.step}}
  {{/each}}
{{/step-manager}}
```

Do note, however, that for this setup to work, you'll need to provide a `currentStep` property on the step manager that tells it what to show first.  In order to show the correct step on the initial render, `currentStep` _must_ be provided.  if it's not done so explicitly  by the user, the addon will actually look at the set of steps provided to fill it in automatically based on the first step that it finds.  However, because you're iterating over some data to define your steps, there's no way to do this at build time so you'll have to define it yourself.

I'm going to close this since I'm not "officially" supporting dynamic names, but I would love to work more with you on figuring out if my suggestions above worked, and if there's anything that I can do to at least partially support it for `v1.0.0`.  What you're doing is something I definitely _want_ to (and tried to) support but there were complications when trying to avoid Ember errors that caused me to have to cut down the initial feature set.
