### ISSUE TITLE
Docs: Link to https://github.com/alexlafroscia/ember-steps/wiki does not work.

### ISSUE THREAD

**Issue by daniel-de-wit** [alexlafroscia/ember-steps#27]
I would like to read some more advanced documentation, but the link is broken unfortunately.

Curious if I can clean-up ( resetting state ) when leaving a step.

**Comment by alexlafroscia** [comment]
Hey @daniel-de-wit! Sorry, I meant to continue fleshing out the docs here but have not gotten around to it yet.

There is the `will-transition` and `did-transition` hooks on the `step-manager` that can be given a closure action (the only difference is that `will-transition` fires before the current step is changed, and returning `false` from it will cancel the transition).  Is that enough?  I've been thinking about adding an action that can be given to the `step` on entrance/exit, would that help your use-case?

**Comment by alexlafroscia** [comment]
I just release version `0.12` that adds an `on-entrance` and `on-exit` action to the step component.  That's probably going to be an easier way to do some cleanup when leaving a particular step.

**Comment by daniel-de-wit** [comment]
@alexlafroscia The hooks you mentioned should be enough for my use cases, thank you very much for taking the time to make this add-on available. This add-on provides more conventions that me and my team love about Ember and it's community. No more bike-shedding!

**Comment by alexlafroscia** [comment]
Awesome! I'm so glad to hear it's working for you. Just a warning, the name of the hook might change in a future version -- I think it's going to become `did-enter` and `did-exit` to better align with the names of the hooks that ember users for things (which generally are prefixed with `did` or `will`).

If it's cool with you, I'm going to close this issue since sprucing up the docs is on my radar already. I'll try to get that taken care of this weekend.
